- name: creating the fact variable playbook
  hosts: all
  become: true
  tasks:
    - name: printing the os name
      debug:
        var: ansible_distribution

    - name: printing the memory free size
      debug:
        var: ansible_memory_mb.real.free

    - name: printing the processor
      debug:
        var: ansible_processor[2]

