- name: setup ntp server
  hosts: all
  become: true
  tasks:
    - name: installing ntp service
      yum:
        name: ntp
        state: present
      when: ansible_distribution == "CentOS"

    - name: installing npt service on ubuntu
      apt:
        name: ntpd
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: starting the ntp service
      service:
        name: ntpd
        state: started
        enabled: true
      when: ansible_os_family == "RedHat"

    - name: starting the ntp service on ubuntu
      service:
        name: ntp
        state: started
        enabled: true
      when: ansible_os_family == "Debian"


