- name: setup httpd server
  hosts: websrv
  become: true
  tasks:
    - name: installing httpd server
      yum:
        name: httpd
        state: present

    - name: starting the httpd service
      service:
        name: httpd
        state: started

    - name: copying the index.html file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 0644
        owner: root
        group: root
